### ISSUE TITLE
Open ID connect as Auth mechanism 

### ISSUE THREAD

**Issue by tatimars** [earthpulse/eotdl#266] opened 2024-11-15 11:39 UTC
Have a look into Open ID connect as AUTH mechanism to interact with Open EO, CDSE, ESA cloud, etc. 
Check what kind of AUTH Provider should be used for this and where the users should register themselves.

**Comment by achtsnits** [comment] 2024-11-15 12:06
duplicate of https://github.com/earthpulse/eotdl/issues/260

on technical level this is understood - one main question is if you want to keep Auth0 and configure further federation from there or just stick to one provider like EGI (which will then federate to e.g. GitHub)

**Closed** 2024-11-15 14:54 UTC
Labels: feature engineering
